### ISSUE TITLE
Scale and Trans bounds

### ISSUE THREAD

**Issue by focomoso** [ssatguru/BabylonJS-EditControl#10]
There's one more addition to the API that I'd need to make this work in my current project which is to add something like a setScaleBounds() and setTransBounds() methods that take a BABYLON.BoundingBox and limit how far you can scale and translate to that box. (I suppose you could do the same with rotationBounds, but it will be harder to specify the limits.)

@ssatguru Is this something you'd like to do or should I give it a shot?

**Comment by ssatguru** [comment]
1) isn't this something which the client can do?client can monitor and reset values  if they exceed some limits
2) Not sure if BABYLON.BoundingBox is appropriate from specifying the bounds? its center it seems is always Zero. May be just just two min, max vectors?
3) for translate and rotate would the constraints be in local or world frame of reference?

**Comment by focomoso** [comment]
1) The trouble with doing this in the client is that the object gets scaled or translated outside the bounds by the control and then "bounces" back when the actionListener is called. If we do it in the control, the object will never get moved or scaled outside the bounds because the error check happens before the render.

2) I was just using the BoundingBox as a convenient placeholder for a minimum and maximum. Two Vector3s would work perfectly well (I can update the pull request if you'd prefer to do it that way). 

3) I was using the world coordinates because constraining locally seems to be an unusual case. Also, I didn't do rotation at all, but can add that. The client would have to pass in a min / max Euler angles.

**Comment by ssatguru** [comment]
Two  Vector3s would be better. BoundingBox comes with too much baggage.
Don't bother about rotation for now,
Instead of demo.html change test.html. Both are exactly the same except demo.html points to stable version of EditControl. I will update demo.html to test.html when I release the new version.
Also if possible keep formatting (space ,tabs etc) the same in the files. That way it is easy to see just the changes,

**Comment by focomoso** [comment]
I have this working with two vectors now, but there's one bug I'm having trouble figuring out.

It works fine in all cases except that if the min vector of any of the scale axes is set to exactly 0, the object will flicker between 0 and some random small size as the mouse moves. It looks as if the diff values being sent to doScaling() are bouncing around. This only happens if the min vectors values are set to exactly 0. Any other arbitrarily small number works fine.

I can submit the request so you can see what's going on, or maybe you might have some idea what could be the problem. I suspect that the problem might be because of the way diff is calculated, but I have no idea why it would only mess up when the min bounds are set to zero.

**Comment by ssatguru** [comment]
can you point me to your new code?

**Comment by focomoso** [comment]
I haven't submitted it yet (because I didn't want to submit a pull request for something I know is broken), but can if you want.

**Comment by ssatguru** [comment]
I am assuming this is the latest code.
[https://github.com/focomoso/BabylonJS-EditControl](https://github.com/focomoso/BabylonJS-EditControl)
Let me checkit out

**Comment by ssatguru** [comment]
Not sure why the issue with min scale bound of zero occurs. Will work on it .
I think feature is worth having despite the issue especially given the fact that there is a workaround for it. I have merged your pull request
Thanks for the contribution.
I will work on rotation bounds when I have some time.

**Comment by focomoso** [comment]
Thanks
