### ISSUE TITLE
editControl.setTransSnapValue doesn't work in sample-global

### ISSUE THREAD

**Issue by apbln** [ssatguru/BabylonJS-EditControl#27]
I'm trying to enable snapping by giving _editControl.setTransSnapValue_ a value but nothing happens. 

I've just put it in the index.js at the transButton, but when I click it, nothing happens ( still no snapping)

 ```
transButton.onclick = function () {
        editControl.enableTranslation();
        editControl.setTransSnap = true;
        editControl.setTransSnapValue = 10;
    };
```

**Comment by ssatguru** [comment]
try the following instead
transButton.onclick = function () {
       editControl.enableTranslation();
       editControl.setTransSnap(true);
       editControl.setTransSnapValue(10);
   };

**Comment by apbln** [comment]
Now the snapping works, but when I drag the object on two axis it isn't dragged diagonally rather in a zigzag-way
