### ISSUE TITLE
Different designs for TwoAxisDraggingButtons (triangles, rectangles)?

### ISSUE THREAD

**Issue by apbln** [ssatguru/BabylonJS-EditControl#28]
At my Playground my TwoAxisDraggingButtons (I just called it this way, hope you know what I mean) are triangles, but using your sample-global I got rectangles which I prefere, how do I change this? And how many designs are there available?

https://www.babylonjs-playground.com/#31M2AP#66

**Comment by ssatguru** [comment]
Sorry, missed this completely. There is only one design. The latest version of edit-control uses the rectangles. To use the latest as global see
https://github.com/ssatguru/BabylonJS-EditControl-Samples/tree/master/sample-global
Not sure how to make the playground work though.
