### ISSUE TITLE
npm / webpack

### ISSUE THREAD

**Issue by accounts-ideashaper** [ssatguru/BabylonJS-EditControl#3]
Hi,

I'm looking at using the EditControl for a project that is built with webpack, which means we can't import the dependencies in a script tag. 

Is there an easy way to package this up as an npm package? Or some other way I can cleanly export it for import? 

Thanks

**Comment by ssatguru** [comment]
should be possible. I will look into it
Thanks

**Comment by accounts-ideashaper** [comment]
I figured it out. All you have to do is import babylon at the top of the .js file:
`import * as BABYLON from 'babylonjs';`

And then export the full path at the bottom:
`export default org.ssatguru.babylonjs.component.EditControl;`

Then you can import the control where you need it with:
`import EditControl from '../lib/EditControl.js';`

and use it as you would otherwise with:
`var ctrl = new EditControl(mesh,camera, canvas, 0.75, false);`

Thanks for doing this...

**Comment by ssatguru** [comment]
Nice.
I am still looking into how to package it into  npm repository.

**Comment by focomoso** [comment]
That would make things much easier...

**Comment by ssatguru** [comment]
I have added this to npm . See readme.
For now I am thinking of leaving this as vanilla "namespaced" JavaScript application. 
Converting it to a nodejs or amd module,  adds module system dependencies .
Doesn't webpack provide a way to add non-module third party apps?

**Comment by focomoso** [comment]
It does, but not using the script tag. I've tried to get this working by using

`import * as EditControl from 'babylonjs-editcontrol';` 

which is how you import Babylon. I had to edit the package.json adding the line:

`"main": "dist/EditControl.js",`

so webpack could find the right file, but the problem is that if the edit control doesn't add Babylon, webpack can't compile it (because BABYLON isn't defined).

**Comment by ssatguru** [comment]
The EditControl  is not a module. It does not export anything and it does not import anything.
WebPack provides "exports-loader"  and "imports-loader"  to add exports and imports to such  apps.
See if this works
```
var EditControl=require("exports-loader?org.ssatguru.babylonjs.component.EditControl!imports-loader?BABYLON=babylonjs!babylonjs-editcontrol/dist/EditControl");
```

you will, ofcourse, have to npm install the following
exports-loader
imports-loader
babylonjs
babylonjs-editcontrol

**Comment by ssatguru** [comment]
have added
```
"main": "dist/EditControl.js",
```
to the package json

**Comment by ssatguru** [comment]
new version adds module support
