### ISSUE TITLE
Adjust scale "speed"

### ISSUE THREAD

**Issue by accounts-ideashaper** [ssatguru/BabylonJS-EditControl#4]
Is it possible to adjust the scale "speed"? That is, change how much a mesh scales given the size of the mouse move? I think this has to do with the scale of the objects in my project, but right now, a tiny move makes the scale shoot out to the horizon.

Thanks,

James

**Comment by ssatguru** [comment]
You are right.
For large mesh a small change in scale can result in large change in dimension.
Currently , "length of mouse move" = "change in scale"
Maybe better would be "length of mouse move" = "change in dimension" and then calculate the new scale  based on the new dimension.
This way you have a precise control of  how much the dimension is changing

**Comment by focomoso** [comment]
That or you could introduce a "scaleFactor" to the api so users can set this how they want.

**Comment by focomoso** [comment]
ps - I'm the same user as above. Was logged in with one of my work accounts when I posted earlier.

**Comment by ssatguru** [comment]
check the latest version in "dist" folder.
See if that is better
scaling "speed" is based on mesh initial size , specifically mesh bounding radius. larger the radius slower the scaling. 
provides the same scaling experience for both small and large meshes

**Comment by focomoso** [comment]
This is definitely an improvement. I wonder, though, if you could use the bounding box's x, y and z widths for the "speed". As it is now, if an object is oblog, scaling along the long dimension seems natural, but along the shorter dimension, it can feel very slow. (Does that make sense?)

**Comment by ssatguru** [comment]
Yes it makes sense. Bounding box will probably be better. Bit more work but doable I think.

**Comment by ssatguru** [comment]
Have switched to Bounding Box. You were right. Better now

**Comment by focomoso** [comment]
Thanks - works great now.
