### ISSUE TITLE
Getting "Error: Eulerian is set to false but the mesh's rotationQuaternion is not set" on creation

### ISSUE THREAD

**Issue by focomoso** [ssatguru/BabylonJS-EditControl#5]
Hi,

I'm getting the error "Error: Eulerian is set to false but the mesh's rotationQuaternion is not set." when I instantiate the editControl with the useEuler set to false (or null):

`    this.editControl = new EditControl(this.scene.meshes[0],this.camera, this.canvas, 1, false);`

If I set it to true, the control works except when rotated with snaps on, in which case I get "Cannot read property 'toEulerAngels' of null" in doRotation() (around line 680).

This only seems to happen when I use webpack to build everything. I can't reproduce it in the playground. 

Any thoughts?

James

**Comment by focomoso** [comment]
Actually, this is happening in the demo currently.

Steps to reproduce:

1. Start the demo
2. Hit 'toggle euler"
3. Check 'snap rotation'
4. Hit 'rotate'
5. manipulate the control

The console fills up with
`Cannot read property 'toEulerAngles' of null`

**Comment by ssatguru** [comment]
this is fixed now
try
[https://ssatguru.github.io/BabylonJS-EditControl/test](https://ssatguru.github.io/BabylonJS-EditControl/test)

**Comment by focomoso** [comment]
Thanks @ssatguru, Great work.
