### ISSUE TITLE
Editor tools interfering with bounding box + re-sizing when camera moves

### ISSUE THREAD

**Issue by Liron-Toledo** [ssatguru/BabylonJS-EditControl#51]
Hey there. I'm not sure if this library is still being supported but thought I'd log an issue just in case. Not sure if this is due to my implementation or not but I'm noticing two issues that are leaving me scratching my head. 

1) The size/scale of the editor tools themselves seems to change based on the position of my camera. 
2) My bounding box implementation (which i will leave the code for below) is being broken whenever the editor tools are active. It seems to react to the changes made by the tools but gets completely separated from the mesh itself. The scale tool ends up controlling its location so perhaps something is wrong there?

Here is a video showing the irregular behaviour: 

https://user-images.githubusercontent.com/32307087/162188826-084e11e3-4664-4d3b-a0f3-aa3af551c45e.mp4

Here is my bounding box code (its pretty much ripped straight from the docs):

```
let childMeshes = parent.getChildMeshes();

    let min = childMeshes[0].getBoundingInfo().boundingBox.minimumWorld;
    let max = childMeshes[0].getBoundingInfo().boundingBox.maximumWorld;

    for(let i=0; i<childMeshes.length; i++){
        let meshMin = childMeshes[i].getBoundingInfo().boundingBox.minimumWorld;
        let meshMax = childMeshes[i].getBoundingInfo().boundingBox.maximumWorld;

        min = BABYLON.Vector3.Minimize(min, meshMin);
        max = BABYLON.Vector3.Maximize(max, meshMax);
    }

    parent.setBoundingInfo(new BABYLON.BoundingInfo(min, max));
    
    parent.showBoundingBox = true;
```

**Comment by Liron-Toledo** [comment]
I've also just come across this issue. When rotating a mesh, the axis that the mesh is translated along our rotated as well despite the tool looking the same. I can't imagine this is desired behaviour?

https://user-images.githubusercontent.com/32307087/162193500-82b7dec6-d3b9-4239-aa8d-490c11c64f67.mp4

**Comment by ssatguru** [comment]
@Liron-Toledo  Is you mesh by any chance a right hand co-ordinate system mesh? a gltf mesh maybe?
You might also want to test out babylonjs gizmo
https://doc.babylonjs.com/divingDeeper/mesh/gizmo

**Comment by Liron-Toledo** [comment]
Hey @ssatguru ya the mesh is a gltf mesh. All my meshes are. I tried out gizmos originally but wanted to try and implement something that closer resembled the transform controls of three.js (which your library does) to me it looks way nicer.

**Comment by ssatguru** [comment]
@Liron-Toledo  gltf mesh are right handed. babylon by default is left hand. So if babylon is brought up as left hand and you load gtlf mesh there can be some issue. try bringing up babylon right handed and see if you still have issue.
I had plans to fix this issue but haven't had time to do so.
if you could provide a  small project  I can look into it.

**Comment by Liron-Toledo** [comment]
Hi again @ssatguru I can confirm that we are already bringing up babylon as right handed. So not sure if thats the cause of the irregular behaviour. Its possible its something on my side that is wrong. Will have to look into it some more.

**Comment by Liron-Toledo** [comment]
Just wanted to update you on my situation. I've managed to fix two of the issues:
1) I managed to fix the bounding box issue by applying the bounding box using `boundingbox.minimum` / `boundingbox.maximum` instead of `minimumWorld` / `maximumWorld` 
2) I managed to fix my rotation issue by attaching the editor controls to the mesh itself rather than its transformNode parent

So the issues were on my side afterall. The only thing I have yet to figure out is why the the editor tool itself grows and shrinks based on the position and orientation of the camera. If you have any idea why this is the case, would greatly appreciate any input you can give.

**Comment by ssatguru** [comment]
"the editor tool itself grows and shrinks" . That is weird. Never had that issue. If you can provide some small test project I can look into that. Hard to say otherwise

**Comment by ssatguru** [comment]
Also how many cameras do you have? And is the camera that you are moving attached to the edit control ?The edit control will appear the same size only when viewed through the camera attached to it

**Comment by Liron-Toledo** [comment]
Hi again! So I only have one camera but I am parenting it to two Transform Nodes (which i do to simplify some mathematical calculations in my render loop). It seems to only grow and shrink the editor tool when rotating and tilting the camera. So i'm starting to think that the parenting must be the cause. 

My camera:
`this.camera = new BABYLON.TargetCamera('camera', new BABYLON.Vector3(0, 0, 0), this.scene)`

The parents:
 ```
// Create camera tilt container
        this.cameraTilt = new BABYLON.TransformNode('camera:' + this.id + ':tilt', this.map.scene)
        this.cameraTilt.position.y = 1.8        // <-- Camera eye height
        this.cameraTilt.rotation.x = 0          // <-- Camera tilt up/down value
        this.camera.parent = this.cameraTilt

        // Create camera container
        this.cameraPosition = new BABYLON.TransformNode('camera:' + this.id + ':position', this.map.scene)
        this.cameraPosition.rotation.y = 0      // <-- Camera rotation value
        this.cameraTilt.parent = this.cameraPosition
```

**Comment by Liron-Toledo** [comment]
Ya the fact that I am applying transformations to the this.cameraTilt when tilting and this.cameraPosition when rotating rather than the camera itself must be whats causing the shrinking and growing
