### ISSUE TITLE
Error when rotating while looking directly at axis

### ISSUE THREAD

**Issue by focomoso** [ssatguru/BabylonJS-EditControl#6]
My project starts with the camera looking directly at the object. If you try to rotate the x by dragging on the red ring (which is essentially a straight line from this angle), you get a "Cannot read property 'x' of null' error on this line:

`var diff = newPos.subtract(this.prevPos);`
`if (diff.x == 0 && diff.y == 0 && diff.z == 0)`

in onPointerMove()

**Comment by ssatguru** [comment]
I am unable to reproduce. can you reproduce on the playground?

**Comment by focomoso** [comment]
The bug seems to be intermittent, but I am able to reproduce it in the demo:

1. Change line 184 in the demo.html to read

`camera = new BABYLON.ArcRotateCamera("ArcRotateCamera", Math.PI / 2, 1.2,`

(I don't get the error using 0, but I do with Math.PI / 2 which makes me think this bug may only be happening with x.)

2. run the demo and switch to 'rotate'.

3. Click on the x ring (red) and move up and down. It doesn't actually rotate and after a couple of tries, I get the error.

Let me know if you still can't reproduce it and I'll try to see if there's something else going on with my system. 

Thanks

**Comment by ssatguru** [comment]
Yes I am able to reproduce the issue.

**Comment by ssatguru** [comment]
This has been fixed.
No errors are thrown.
Of course you still can't rotate the mesh around the axis you are directly looking at but then that is an "expected" behavior. :)
Also when looking directly at the axis the the axis rotation  guide circles weren't showing properly - half red , half green. That has been fixed too.
