### ISSUE TITLE
Trouble compiling from typescript

### ISSUE THREAD

**Issue by focomoso** [ssatguru/BabylonJS-EditControl#7]
I created my own fork (to try to help figure out the npm stuff), but can't get the typescript to compile.

npm install works, but when I run npm run compile I get a ton of "Cannot find namespace 'BABYLON'." errors.

**Comment by ssatguru** [comment]
you probably need to do a npm install first. That will install the BABYLON files including the BABYLON typescript definition file

**Comment by ssatguru** [comment]
I am on windows. works fine for me.

**Comment by focomoso** [comment]
How is BABYLON supposed to be defined for the .ts file? I don't see an import statement.

**Comment by focomoso** [comment]
If I add
`import * as BABYLON from 'babylonjs';`
in EditControl.ts, I get a million errors:
`node_modules/babylonjs/dist/preview release/babylon.module.d.ts(73,25): error TS1005: '=' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(73,42): error TS1005: ';' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(74,25): error TS1005: '=' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(74,41): error TS1005: ';' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(110,25): error TS1005: '=' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(110,30): error TS1005: ';' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(111,25): error TS1005: '=' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(111,31): error TS1005: ';' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(112,25): error TS1005: '=' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(112,29): error TS1005: ';' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(113,25): error TS1005: '=' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(113,30): error TS1005: ';' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(114,25): error TS1005: '=' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(114,31): error TS1005: ';' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(115,25): error TS1005: '=' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(115,32): error TS1005: ';' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(116,25): error TS1005: '=' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(116,31): error TS1005: ';' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(117,25): error TS1005: '=' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(117,33): error TS1005: ';' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(125,25): error TS1005: '=' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(125,29): error TS1005: ';' expected.
node_modules/babylonjs/dist/preview release/babylon.module.d.ts(126,25): error TS1005: '=' expected.`

(on and on for the entire file)

And I get an npm ERR! that the build failed.

~~But it actually does compile.~~

No, it's not compiling. Those were older files.

**Comment by ssatguru** [comment]
couple of points
1) you do not need an import statement. 
If the typescript transpiler finds a type definition  file in its "path" then it will load all definitions from it and use it.  
In our case the babylonjs.d.ts is in the node_modules folder and is auto found by the transpiler ( see [https://www.typescriptlang.org/docs/handbook/module-resolution.html](https://www.typescriptlang.org/docs/handbook/module-resolution.html))  
You only need an "import *" if you want to call BABYLON module by some other name.
In which case the import statement would be
```
import * as MYNAME from "BABYLON"
```
2) the statement  
```
 import * as BABYLON from 'babylonjs';  
```
tells the transpiler that you are trying to call a module named "babylonjs" as "BABYLON". 
But there is no module called "babylonjs"
Note that there are two format of import statements
```
import {abc} from 'somepath/mymodule';  
or
import {abc} from 'mymodule';  
```
The first provides a path to a .ts file. Here it is "somepath/mymodule.ts" file. The extension .ts is dropped
You would normally use this if you have the typescript source code
The second is used if you have a type definition file. In which case "mymodule" itself would be defined in a .d.ts type definition file .
the .d.ts file would be auto discovered if it is on a standard path. If not then you can provide the path using the triple slash notation
```
/// <reference path=”somepath/mymodule.d.ts” />
```

**Comment by focomoso** [comment]
Okay - it turns out that it was actually compiling despite all the errors. Not sure why tsc keeps giving "error TS2503: Cannot find namespace 'BABYLON'" and "error TS4000: Import declaration 'AbstractMesh' is using private name 'BABYLON'", but I'm able to get things working.

Thanks for walking me through this.
